### ISSUE TITLE
Issue with Swift_Mime_Message

### ISSUE THREAD

**Issue by auto-holder** [mtcextendee/mautic-random-smtp-bundle#4]
I get the following error when trying to install running 4.1.1:
Compile Error: Could not check compatibility between MauticPlugin\MauticRandomSmtpBundl  
  e\Swiftmailer\Transport\RandomSmtpTransport::send(Swift_Mime_Message $message, &$failed  
  Recipients = NULL) and Swift_Transport_AbstractSmtpTransport::send(Swift_Mime_SimpleMes  
  sage $message, &$failedRecipients = NULL), because class Swift_Mime_Message is not available

**Comment by kuzmany** [comment]
Repository was not maintenance  2019, then does not support M4.
If you have budget for that, please write to me http://mtcextendee.com/contact/ and I can make it as paid job.

Thank you for understanding
